### ISSUE TITLE
组件命名的问题

### ISSUE THREAD

**Issue by cnsnake11** [sunnylqm/react-native-coding-style#1]
非常感谢你们提供的规范，我这有个问题想请教一下。

扩展名: 使用.js作为js文件的扩展名。如果同一个文件夹下有同名而不同作用的js文件，则通过中缀（小写）进一步区分，例如：HomeView.component.js,HomeView.style.js,HomeView.action.js等。

如果是这样编写文件名，那import之后我该如何命名比较好呢？

比如，import aaa from 'HomeView.component.js' 中的aaa 我该如何命名比较好呢？

**Comment by sunnylqm** [comment]
```
import HomeView from 'HomeView.component.js';
import HomeViewStyle from 'HomeView.style.js';
import * as HomeViewAction from 'HomeView.action.js';
```
我大概会这么命名

**Comment by cnsnake11** [comment]
非常感谢
