### ISSUE TITLE
私有函数加不加下划线前后矛盾

### ISSUE THREAD

**Issue by macoscoder** [sunnylqm/react-native-coding-style#2]
<img width="539" alt="2016-03-17 2 15 12" src="https://cloud.githubusercontent.com/assets/5967849/13838019/7d5aba58-ec4b-11e5-9ac5-57cfb093edfb.png">
<img width="235" alt="2016-03-17 2 15 35" src="https://cloud.githubusercontent.com/assets/5967849/13838018/7d5a6e40-ec4b-11e5-8e0b-83d70b0532b9.png">

**Comment by sunnylqm** [comment]
感谢提醒，但这里我基本已经没有维护，建议直接使用airbnb的最新eslint设定即可
https://github.com/airbnb/javascript

**Comment by macoscoder** [comment]
感谢
